## Usar arrays con numpy

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
print(f"\nEsto es una lista: {lista}.", 
      f"\nEl primer elemento de la lista es: {lista[0]}.", 
      f"\nEl tipo de dato de esta lista es: {type(lista)}.", 
      f"\nEl tercer elemento de la lista sumado con el séptimo elemento de la lista es: {lista[2]+lista[6]}.")


Esto es una lista: [1, 2, 3, 4, 5, 6, 7, 8, 9]. 
El primer elemento de la lista es: 1. 
El tipo de dato de esta lista es: <class 'list'>. 
El tercer elemento de la lista sumado con el séptimo elemento de la lista es: 10.


### $np.array()$
Transforma una lista $l$ a un array.
$$np.array(l)$$

In [3]:
arr = np.array(lista)
print(f"\nEsto es un array creado usando numpy: {arr}.", 
      f"\nEl primer elemento del array es : {arr[0]}, y el último elemento es: {arr[-1]}.", 
      f"\nEl tipo de dato del array es : {type(arr)}.", 
      f"\nEl primer elemento del array sumado con el sexto es: {arr[0]+arr[5]}.", 
      f"\nUn nuevo array que va desde el segundo elemento hasta es sexto es: {arr[1:6]}.", 
      f"\nUn nuevo array que va desde el primer elemento hasta es quinto es: {arr[:5]}.", 
      f"\nUn nuevo array que va desde el tercer elemento hasta el último elemento del array es: {arr[3:]}."
      f"\nUn nuevo array creado a partir del primero que va tomando elementos de tres en tres: {arr[::3]}."
      f"\nUn nuevo array que consta de los cuatro últimos elementos del original: {arr[-4:]}.")


Esto es un array creado usando numpy: [1 2 3 4 5 6 7 8 9]. 
El primer elemento del array es : 1, y el último elemento es: 9. 
El tipo de dato del array es : <class 'numpy.ndarray'>. 
El primer elemento del array sumado con el sexto es: 7. 
Un nuevo array que va desde el segundo elemento hasta es sexto es: [2 3 4 5 6]. 
Un nuevo array que va desde el primer elemento hasta es quinto es: [1 2 3 4 5]. 
Un nuevo array que va desde el tercer elemento hasta el último elemento del array es: [4 5 6 7 8 9].
Un nuevo array creado a partir del primero que va tomando elementos de tres en tres: [1 4 7].
Un nuevo array que consta de los cuatro últimos elementos del original: [6 7 8 9].


### Podemos crear matrices con numpy

In [5]:
matriz = [[1,0],[0,-1]]
print(f"\nEsto es una lista que contiene listas: {matriz}.", 
      f"\nEl primer elemento de esta lista es: {matriz[0]}.", 
      f"\nEl tipo de dato de esta lista es : {type(matriz)}.", 
      f"\nSumar los dos elementos de la lista genera una lista que encadena estos dos elementos: {matriz[0]+matriz[1]}.")


Esto es una lista que contiene listas: [[1, 0], [0, -1]]. 
El primer elemento de esta lista es: [1, 0]. 
El tipo de dato de esta lista es : <class 'list'>. 
Sumar los dos elementos de la lista genera una lista que encadena estos dos elementos: [1, 0, 0, -1].


In [6]:
npmatriz = np.array(matriz)
print(f"\nEsto es una matriz creada con numpy: \n{npmatriz}.", 
      f"\nLa primera fila de esta matriz es: {npmatriz[0]}.", 
      f"\nEl tipo de dato de la matriz es: {type(npmatriz)}.", 
      f"\nLa suma de la primera fila con la segunda fila es: {npmatriz[0]+npmatriz[1]}.")


Esto es una matriz creada con numpy: 
[[ 1  0]
 [ 0 -1]]. 
La primera fila de esta matriz es: [1 0]. 
El tipo de dato de la matriz es: <class 'numpy.ndarray'>. 
La suma de la primera fila con la segunda fila es: [ 1 -1].


In [7]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
npmat = np.array(mat)
print(f"\nEsto es una matriz de 3x3: \n{npmat}."
      f"\nUna matriz que contiene las dos últimas filas de la primera: \n{npmat[1:]}"
      f"\nUna matriz de 2x2 que contiene las dos primeras columnas de las dos últimas filas: \n{npmat[1:,0:2]}\n")


Esto es una matriz de 3x3: 
[[1 2 3]
 [4 5 6]
 [7 8 9]].
Una matriz que contiene las dos últimas filas de la primera: 
[[4 5 6]
 [7 8 9]]
Una matriz de 2x2 que contiene las dos primeras columnas de las dos últimas filas: 
[[4 5]
 [7 8]]

