## Tipos de datos.

In [ ]:
import numpy as np

Un array de enteros:

In [ ]:
arrInt = np.array([1,2,3,9])
arrInt.dtype, arrInt

(dtype('int64'), array([1, 2, 3, 9]))

Se puede definir el tipo de dato deseado para el array con el comando $dtype$:

In [ ]:
arrFloat = np.array([1,2,3,9], dtype='float64')
arrFloat.dtype, arrFloat

(dtype('float64'), array([1., 2., 3., 9.]))

Se puede cambiar el tipo de dato del array:

In [ ]:
arr = np.array([0,1,2,3,4,5])
arr.dtype, arr

(dtype('int64'), array([0, 1, 2, 3, 4, 5]))

In [ ]:
arr = arr.astype(np.float64)
arr.dtype, arr

(dtype('float64'), array([0., 1., 2., 3., 4., 5.]))

In [ ]:
arr = arr.astype(np.bool_)
arr.dtype, arr

(dtype('bool'), array([False,  True,  True,  True,  True,  True]))

In [ ]:
arr = arr.astype(np.str_)
arr.dtype, arr

(dtype('<U5'),
 array(['False', 'True', 'True', 'True', 'True', 'True'], dtype='<U5'))

El array solo puede tener un único tipo de dato.

## Dimensiones.

Un array de un solo valor tiene dimensión 0:

In [ ]:
scalar = np.array(2)
print(f"El array scalar = {scalar} tiene dimensión {scalar.ndim}.")

El array scalar = 2 tiene dimensión 0.


En numpy, un array que contiene una lista tiene dimensión 1:

In [ ]:
vector = np.array([1,2,3])
print(f"El vector = {vector} tiene dimensión {vector.ndim}.")

El vector = [1 2 3] tiene dimensión 1.


En numpy, un array que contiene una lista de listas tiene dimensión 2:

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(f"La matriz = \n{matriz} \ntiene dimensión {matriz.ndim}.")

La matriz = 
[[1 2 3]
 [4 5 6]] 
tiene dimensión 2.


En numpy, los arrays son tensores de orden 0, 1, 2, 3, ... :

In [ ]:
tensor = np.array([[[1,0,0],[0,1,0],[0,0,1]],[[-1,0,0],[0,-1,0],[0,0,-1]]])
print(f"El tensor = \n{tensor}\ntiene orden {tensor.ndim}.")

El tensor = 
[[[ 1  0  0]
  [ 0  1  0]
  [ 0  0  1]]

 [[-1  0  0]
  [ 0 -1  0]
  [ 0  0 -1]]]
tiene orden 3.


Se puede cambiar la dimensión del array de numpy:

In [ ]:
vec = np.array([1,2,3],ndmin=4)
print(f"El vector vec = {vec} tiene dimensión {vec.ndim}.")

El vector vec = [[[[1 2 3]]]] tiene dimensión 4.


Se puede expandir la dimensión de un array en diferentes 'ejes':

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(f"Diré entre comillas que el vector expand = \n{expand} \n'se convirtió en una matriz fila' y su dimensión en numpy es {expand.ndim}.")
expand = np.expand_dims(np.array([1,2,3]),axis=1)
print(f"De manera similar, el vector expand = \n{expand} \n'se convirtió en una matriz columna' y su dimensión en numpy es {expand.ndim}.")

Diré entre comillas que el vector expand = 
[[1 2 3]] 
'se convirtió en una matriz fila' y su dimensión en numpy es 2.
De manera similar, el vector expand = 
[[1]
 [2]
 [3]] 
'se convirtió en una matriz columna' y su dimensión en numpy es 2.


Se puede también igualar la dimensión de un array con la de otro:

In [ ]:
matriz1 = np.array([[1,0],[0,1]])
vector1 = np.array([2,3])
print(f"Matriz1 = \n{matriz1}\nes una matriz y vector1 = {vector1} es un vector.")
vector1 = np.squeeze(matriz1)
print(f"Con la función squeeze se puede igualar ma dimensión del vector1 con la de la matriz1 obteniendo como resultado:\nvector1 = \n{vector1}")

Matriz1 = 
[[1 0]
 [0 1]]
es una matriz y vector1 = [2 3] es un vector.
Con la función squeeze se puede igualar ma dimensión del vector1 con la de la matriz1 obteniendo como resultado:
vector1 = 
[[1 0]
 [0 1]]


## La función shape

La función shape muestra el numero de entradas posibles en cada dimensión de un array.
Por ejemplo el tensor definido anteriormente tiene $2$ matrices cada una de dimensión $3 \times 3$.

In [ ]:
print(tensor.shape, vector1.shape)

(2, 3, 3) (2, 2)
