## Crear listas directamente de numpy

In [2]:
import numpy as np

Un array de un rango: $arreglo = np.arrange(\text{inicio},\text{ fin},\text{ pasos})$.

In [12]:
arr = np.arange(3,98,2)
print(arr)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97]


Un vector de ceros: $vceros = np.zeros(\text{numero de ceros})$.

In [16]:
vceros = np.zeros(6)
print(vceros)

[0. 0. 0. 0. 0. 0.]


Una matriz de ceros: $mceros = np.zeros(\text{número der filas}, \text{número de columnas})$.

In [19]:
mceros = np.zeros((3,5))
print(mceros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Un tensor de ceros: $tceros = np.zeros(\text{número de matrices}, \text{filas por matriz}, \text{columnas por matriz})$.

In [21]:
tceros = np.zeros((2,3,5))
print(tceros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


Podemos seguir el mismo razonamiento con arreglos de números uno.
Por ejemplo, un tensor de orden 4 donde todas sus entradas son 1:
$\\ tunos = np.ones((\text{número de tensores de orden tres}, \text{tensor de orden tres}))$
$$T_{ijkl} = 1, \forall i, j, k, l.$$

In [27]:
tunos = np.ones((2,3,2,5)) # dos arreglos de tres matrices cada una con dos filas y cinco columnas
print(tunos)

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


## Linspace

Genera la división de un rango en un número de partes deseado.

Ejemplo: un arreglo de 50 elementos que inicia en el 2 y termina en el tres:

In [30]:
intervalo2_3 = np.linspace(2,3,50)
print(intervalo2_3, "\n", len(intervalo2_3))

[2.         2.02040816 2.04081633 2.06122449 2.08163265 2.10204082
 2.12244898 2.14285714 2.16326531 2.18367347 2.20408163 2.2244898
 2.24489796 2.26530612 2.28571429 2.30612245 2.32653061 2.34693878
 2.36734694 2.3877551  2.40816327 2.42857143 2.44897959 2.46938776
 2.48979592 2.51020408 2.53061224 2.55102041 2.57142857 2.59183673
 2.6122449  2.63265306 2.65306122 2.67346939 2.69387755 2.71428571
 2.73469388 2.75510204 2.7755102  2.79591837 2.81632653 2.83673469
 2.85714286 2.87755102 2.89795918 2.91836735 2.93877551 2.95918367
 2.97959184 3.        ] 
 50


## La matriz identidad

Genera la matriz identidad con la sentencia eye: $\\ id = np.eye(\text{numero de filas}) \\ \text{(El número de filas es igual al número de columnas)}$.


In [32]:
id = np.eye(5)
print(id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Random

Podemos crear tensores de cualquier orden con entradas aleatorias.

### rand()

Genera valores aleatorios entre el cero y uno.

In [35]:
vrand = np.random.rand(3)
print(f"vrand = \n{vrand}\nes un vector con tres entradas generadas de manera aleatoria.")

vran = 
[0.0649457  0.06004603 0.32161784]
es un vector con tres entradas generadas de manera aleatoria.


In [38]:
mrand = np.random.rand(2,3)
print(f"mrand = \n{mrand}\nes es una matriz de dos filas y tres columnas cuyas entradas son valores generados de manera aleatoria.")

mrand = 
[[0.43118804 0.57142473 0.65918108]
 [0.06285374 0.03394474 0.81672096]]
es es una matriz de dos filas y tres columnas cuyas entradas son valores generados de manera aleatoria.


In [39]:
trand = np.random.rand(2,2,3)
print(f"trand = \n{trand}\nes es un tensor con dos arreglos matriciales de dos filas y tres columnas cuyas entradas son valores generados de manera aleatoria.")

trand = 
[[[0.03728512 0.83871675 0.5793754 ]
  [0.40103356 0.13648335 0.74984019]]

 [[0.22068306 0.30368832 0.540394  ]
  [0.14777424 0.96757323 0.88852077]]]
es es un tensor con dos arreglos matriciales de dos filas y tres columnas cuyas entradas son valores generados de manera aleatoria.


### randint()

Podemos crear tensores de cualquier orden con entradas aleatorias seleccionadas de un rango en especifico.

In [48]:
trandint = np.random.randint(10,30,(2,3,2,5))
print(f"trandint =\n{trandint}\nes un tensor de orden cuatro.\nConsta de dos arreglos de tres matrices, cada matriz tiene dos filas y cinco columnas.")

trandint =
[[[[17 15 10 14 18]
   [20 11 24 19 22]]

  [[29 20 22 29 27]
   [29 16 19 23 25]]

  [[23 18 17 23 19]
   [28 20 24 21 20]]]


 [[[17 12 27 23 27]
   [28 29 19 11 20]]

  [[19 11 16 17 10]
   [13 29 22 10 28]]

  [[26 11 17 14 26]
   [13 26 15 15 14]]]]
es un tensor de orden cuatro.
Consta de dos arreglos de tres matrices, cada matriz tiene dos filas y cinco columnas.
