## Shape y reshape

In [1]:
import numpy as np

### Shape

Shape muestra las dimensiones del arreglo creado:

In [4]:
matriz = np.array([[1,2,3],[4,5,6]])
print(f"Las dimensiones de la matriz = \n{matriz}\nson: {matriz.shape}")

Las dimensiones de la matriz = 
[[1 2 3]
 [4 5 6]]
son: (2, 3)


### Reshape

Reshape nos permite redimensionar un arreglo.

In [5]:
print(f"Se puede redimensionar la matriz de 2x3 a 3x2\nmatriz =\n{matriz.reshape(3,2)}.")

Se puede redimensionar la matriz de 2x3 a 3x2
matriz =
[[1 2]
 [3 4]
 [5 6]].


Hay dos métodos para hacer reshape.

In [17]:
matriz1 = np.reshape(matriz,(3,2),'C') # el método 'C' redimensiona como en lenguaje C
print(matriz, '\n', matriz1) # el método 'C' recorre las filas para transformarlas en filas

[[1 2 3]
 [4 5 6]] 
 [[1 2]
 [3 4]
 [5 6]]


In [14]:
matriz2 = np.reshape(matriz,(3,2),'F') # el método 'F' redimensiona como en lenguaje Fortran
print(matriz, '\n', matriz2) # el método F recorre las columnas y para transformarlas en columnas

[[1 2 3]
 [4 5 6]] 
 [[1 5]
 [4 3]
 [2 6]]


In [18]:
matriz3 = np.reshape(matriz,(3,2),'A') # el método 'A' redimensiona según esté optimizado el dispositivo que se está usando
print(matriz, '\n', matriz3) # en este caso el método óptimo es el 'C'

[[1 2 3]
 [4 5 6]] 
 [[1 2]
 [3 4]
 [5 6]]
