## Funciones principales de NumPy

### Entorno de trabajo:

In [37]:
import numpy as np

In [38]:
vector = np.random.randint(5,25,12)
print(vector)

[22 14 20 18  8 12 21 15 20  5  9  5]


Definimos una matriz $M$ partiendo del vector anterior:

In [39]:
matriz = vector.reshape(3,4)
print(matriz)

[[22 14 20 18]
 [ 8 12 21 15]
 [20  5  9  5]]


Una segunda matriz $M2$

In [81]:
matriz2 = np.random.randint(10,20,(3,4))
print(matriz2)

[[19 12 17 11]
 [15 15 12 19]
 [12 11 13 10]]


### El máximo

#### max()
El valor máximo

Obtener el elemento mayor de un array:$$arreglo.max()$$

In [40]:
max = matriz.max()
print(max)

22


En el eje 0 encontramos las columnas y el eje 1 las filas.

Podemos obtener los máximos de cada eje, es decir, los máximos de cada fila o de cada columna especificando el eje de interés: $$arreglo.max(\,i\,) \hspace{0.4 cm} i = 0, 1 \hspace{0.1 cm} (\,\text{0 y 1 son los ejes}\,).$$

In [41]:
print(f"Un arreglo con los valores máximos de cada columna de la matriz M: {matriz.max(0)}.")
print(f"Un arreglo con los valores máximos de cada fila de la matriz M: {matriz.max(0)}.")

Un arreglo con los valores máximos de cada columna de la matriz M: [22 14 21 18].
Un arreglo con los valores máximos de cada fila de la matriz M: [22 14 21 18].


#### argmax()
El índice del valor máximo

Podemos obtener el índice del máximo elemento de un arreglo, el indice recorre las filas de izquierda a derecha y de arriba hacia abajo: $$arreglo.argmax()$$

In [42]:
print(matriz.argmax())

0


Podemos obtener el índice del máximo de cada fila o columna especificando el eje a analizar: $$arreglo.argmax(\,i\,) \hspace{0.4 cm} i = 0, 1 \hspace{0.1 cm} (\,\text{0 y 1 son los ejes}\,).$$

In [43]:
print("Un arreglo con el índice del máximo de cada columna de la matriz:", matriz.argmax(0))
print("Un arreglo con el índice del máximo de cada fila de la matriz:", matriz.argmax(1))

Un arreglo con el índice del máximo de cada columna de la matriz: [0 0 1 0]
Un arreglo con el índice del máximo de cada fila de la matriz: [0 2 0]


### El mínimo

#### min()
Nos da el valor mínimo.

Obtener el elemento menor de un array:$$arreglo.min()$$

In [44]:
print(matriz.min())

5


Podemos obtener los mínimos de cada eje, es decir, los mínimos de cada fila o de cada columna especificando el eje de interés: $$arreglo.min(\,i\,) \hspace{0.4 cm} i = 0, 1 \hspace{0.1 cm} (\,\text{0 y 1 son los ejes}\,).$$

In [45]:
print(f"Un arreglo con los valores mínimos de cada columna de la matriz M: {matriz.min(0)}.")
print(f"Un arreglo con los valores mínimos de cada fila de la matriz M: {matriz.min(1)}.")

Un arreglo con los valores mínimos de cada columna de la matriz M: [8 5 9 5].
Un arreglo con los valores mínimos de cada fila de la matriz M: [14  8  5].


#### argmin()
Nos da el índice del valor mínimo.

Podemos obtener el índice del menor elemento de un arreglo: $$arreglo.argmin()$$

In [46]:
print(matriz.argmin())

9


Podemos obtener el índice del mínimo de cada fila o columna especificando el eje a analizar: $$arreglo.argmin(\,i\,) \hspace{0.4 cm} i = 0, 1 \hspace{0.1 cm} (\,\text{0 y 1 son los ejes}\,).$$

In [47]:
print("Un arreglo con el índice del mínimo de cada columna de la matriz:", matriz.argmin(0))
print("Un arreglo con el índice del mínimo de cada fila de la matriz:", matriz.argmin(1))

Un arreglo con el índice del mínimo de cada columna de la matriz: [1 2 2 2]
Un arreglo con el índice del mínimo de cada fila de la matriz: [1 0 1]


### El rango
Podemos obtener la diferencia entre el máximo y el mínimo.

#### ptp()

Obtener rango un array (función $\text{peak to peak}$):$$arreglo.ptp()$$

In [48]:
print(matriz.ptp())

17


Podemos obtener el rango en cada eje, es decir, el ragno de valores en cada fila o cada columna especificando el eje de interés: $$arreglo.ptp(\,i\,) \hspace{0.4 cm} i = 0, 1 \hspace{0.1 cm} (\,\text{0 y 1 son los ejes}\,).$$

In [49]:
print(f"Un arreglo con el rango de valores en cada columna de la matriz M: {matriz.min(0)}.")
print(f"Un arreglo con el rango de valores en cada fila de la matriz M: {matriz.min(1)}.")

Un arreglo con el rango de valores en cada columna de la matriz M: [8 5 9 5].
Un arreglo con el rango de valores en cada fila de la matriz M: [14  8  5].


### El percentil
Los percentiles indican el porcentaje de puntuaciones que caen por debajo de cierto valor.

#### np.percentile()

Del rango de valores del arreglo, lo divide en 100 y toma el percentil $i$ indicado entre el a al 100: $$np.percentile(arreglo,i_{percentil})$$

In [50]:
percentiles = []
for i in range(101):
    percentiles.append(np.percentile(matriz,i))
print(np.array(percentiles))

[ 5.    5.    5.    5.    5.    5.    5.    5.    5.    5.    5.3   5.63
  5.96  6.29  6.62  6.95  7.28  7.61  7.94  8.09  8.2   8.31  8.42  8.53
  8.64  8.75  8.86  8.97  9.24  9.57  9.9  10.23 10.56 10.89 11.22 11.55
 11.88 12.14 12.36 12.58 12.8  13.02 13.24 13.46 13.68 13.9  14.06 14.17
 14.28 14.39 14.5  14.61 14.72 14.83 14.94 15.15 15.48 15.81 16.14 16.47
 16.8  17.13 17.46 17.79 18.08 18.3  18.52 18.74 18.96 19.18 19.4  19.62
 19.84 20.   20.   20.   20.   20.   20.   20.   20.   20.   20.02 20.13
 20.24 20.35 20.46 20.57 20.68 20.79 20.9  21.01 21.12 21.23 21.34 21.45
 21.56 21.67 21.78 21.89 22.  ]


### La media

#### np.mean()

Podemos calcular la media de los valores de un arreglo: $$media = np.mean(arreglo)$$

In [76]:
print(np.mean(matriz)) # la media de todo el arreglo
print(np.mean(matriz,0)) # la media por cada columna
print(np.mean(matriz,1)) # la media por cada fila

14.083333333333334
[12.33333333 13.         14.66666667 16.33333333]
[ 6.75 14.75 20.75]


### La mediana

#### np.median()

Podemos calcular la mediana de los valores de un arreglo: $$medians = np.median(arreglo)$$

In [59]:
print(np.median(matriz))

14.5


Podemos obtener la mediana de cada fila o columna especificando el eje a analizar: $$np.median(arreglo, \ i) \hspace{0.4 cm} i = 0, 1 \hspace{0.1 cm} (\,\text{0 y 1 son los ejes}\,).$$

In [75]:
print(f"Un arreglo con la mediana de cada columna de la matriz M: {np.median(matriz,0)}.")
print(f"Un arreglo con la mediana de cada fila de la matriz M: {np.median(matriz,1)}.")

Un arreglo con la mediana de cada columna de la matriz M: [12. 14. 15. 18.].
Un arreglo con la mediana de cada fila de la matriz M: [ 6.5 14.5 20.5].


### Desviación estándar
La desviación estándar se utiliza para calcular la variación o dispersión en la que los puntos de datos individuales difieren de la media. 

#### np.std()

Podemos calcular la desviación estándar de los datos de un array:
$$\text{desviación estándar} = np.std(arreglo)$$

In [63]:
print(np.std(matriz)) # la desviación estándar de todo el arreglo
print(np.std(matriz,0)) # la desviación estándar por cada columna
print(np.std(matriz,1)) # la desviación estándar por cada fila

5.97854961972848
[6.18241233 3.8586123  5.43650214 5.55777733]
[2.95803989 4.74341649 6.13901458]


### La varianza

La varianza es una medida de dispersión que representa la variabilidad de una serie de datos con respecto a su media. 

#### np.var()

In [64]:
print(np.var(matriz)) # la varianza de todo el arreglo
print(np.var(matriz,0)) # la varianza estándar por cada columna
print(np.var(matriz,1)) # la varianza estándar por cada fila

35.74305555555555
[38.22222222 14.88888889 29.55555556 30.88888889]
[ 8.75   22.5    37.6875]


### Concatenar

#### np.concatenate()

Podemos concatenar arreglos: $$\text{nuevo arreglo} = np.concatenate((arreglo1,\ arreglo2))$$

In [84]:
matriz3 = np.concatenate((matriz,matriz2))
print(matriz3,np.shape(matriz3))

[[ 5  5  8  9]
 [12 14 15 18]
 [20 20 21 22]
 [19 12 17 11]
 [15 15 12 19]
 [12 11 13 10]] (6, 4)


Podemos concatenar arreglos según su eje (eje 0 agrega filas y eje 1 agrega columnas): $$\text{nuevo arreglo} = np.concatenate((arreglo1,\ arreglo2),axis=i) \hspace{0.3 cm} i  = 0,\ 1.$$

In [93]:
matriz4 = np.concatenate((matriz,matriz2),axis=0)
print(matriz4,np.shape(matriz4))
matriz5 = np.concatenate((matriz,matriz2),axis=1)
print(matriz5,np.shape(matriz5))


[[ 5  5  8  9]
 [12 14 15 18]
 [20 20 21 22]
 [19 12 17 11]
 [15 15 12 19]
 [12 11 13 10]] (6, 4)
[[ 5  5  8  9 19 12 17 11]
 [12 14 15 18 15 15 12 19]
 [20 20 21 22 12 11 13 10]] (3, 8)


### La transpuesta

### .T

Para obtener la matriz transpuesta:

In [98]:
print(matriz4.T,np.shape(matriz4.T))
print(matriz5.T,np.shape(matriz5.T))

[[ 5 12 20 19 15 12]
 [ 5 14 20 12 15 11]
 [ 8 15 21 17 12 13]
 [ 9 18 22 11 19 10]] (4, 6)
[[ 5 12 20]
 [ 5 14 20]
 [ 8 15 21]
 [ 9 18 22]
 [19 15 12]
 [12 15 11]
 [17 12 13]
 [11 19 10]] (8, 3)
