## Copy

### Entorno de trabajo

In [45]:
import numpy as np

Definimos un arreglo

In [46]:
matriz = np.random.randint(5,25,(5,5))
print(matriz)

[[ 5 19  8 20 10]
 [ 6 15  7  9 24]
 [23  5 20  6 15]
 [18 11  6 17  9]
 [22 16 16 23  5]]


In [50]:
matriz2 = np.random.randint(5,25,(5,5))
print(matriz2)

[[ 7 15  8  6 18]
 [ 7  7 13 21 10]
 [18 13  6 23 21]
 [10 21 13 24 15]
 [14 19  6 19 14]]


También definimos un nuevo arreglo partiendo elementos del primero:

In [47]:
submatriz = matriz[0:3,0:3]
print(submatriz)

[[ 5 19  8]
 [ 6 15  7]
 [23  5 20]]


Si modificamos el nuevo arreglo aun que se le ha asignado a una nueva variable:

In [48]:
submatriz[:] = 0
print(submatriz)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Se modifica el arreglo original:

In [49]:
print(matriz)

[[ 0  0  0 20 10]
 [ 0  0  0  9 24]
 [ 0  0  0  6 15]
 [18 11  6 17  9]
 [22 16 16 23  5]]


#### copy()

Para evitar modificar el objeto original podemos hacer una copia con el contenido del arreglo de nuestro interés.

In [55]:
submatriz2 = matriz2.copy()
submatriz2 = submatriz2[0:3,0:3]
print(submatriz2)

[[ 7 15  8]
 [ 7  7 13]
 [18 13  6]]


In [57]:
submatriz2[:] = 1
print(submatriz2)
print(f"La matriz \n{matriz2}\ncon la que fue generada la matriz anterior no se modifica si se trabaja con una copia.")

[[1 1 1]
 [1 1 1]
 [1 1 1]]
La matriz 
[[ 7 15  8  6 18]
 [ 7  7 13 21 10]
 [18 13  6 23 21]
 [10 21 13 24 15]
 [14 19  6 19 14]]
con la que fue generada la matriz anterior no se modifica si se trabaja con una copia.


## Para evitar perder información hay que usar el comando copy()