## Operaciones

In [16]:
import numpy as np

### Con vectores

In [17]:
vector = np.array([1,2])
print(vector)

[1 2]


#### Suma

In [18]:
vector2 = vector + vector
print(vector2)

[2 4]


#### Producto escalar

In [19]:
vector2 = 3*vector
print(vector2)

[3 6]


#### Producto punto

In [20]:
vector2 = vector*vector
print(vector2)

[1 4]


### Con matrices

In [21]:
matriz = np.random.randint(1,5,(2,3))
print(matriz)

[[1 2 1]
 [1 1 4]]


#### Suma

In [22]:
matriz2 = matriz+matriz
print(matriz2)

[[2 4 2]
 [2 2 8]]


#### Producto escalar

In [24]:
matriz2 = 3*matriz
print(matriz2)

[[ 3  6  3]
 [ 3  3 12]]


#### Producto punto

In [26]:
matriz2 = matriz*matriz
print(matriz2)

[[ 1  4  1]
 [ 1  1 16]]


#### Producto de matrices
Tener en cuenta que en el producto de dos matrices $M1$ y $M2$, si las dimensiones de la matriz $M1$ son $n\times p$, las dimensiones de la matriz $M2$ deben ser $p\times n, \ \text{donde }n \ \text{y } p \in \mathbb N$. El resultado $M = M1\times M2$ tiene dimensiones $n\times n$.

In [29]:
matriz2 = np.matmul(matriz,matriz.T)
print(matriz2)

[[ 6  7]
 [ 7 18]]


### Con tensores

In [32]:
tensor = np.random.randint(-1,2,(2,3,3))
print(tensor)

[[[-1  0  1]
  [ 1  1  0]
  [ 0  0 -1]]

 [[ 0  1  1]
  [ 1  0 -1]
  [-1 -1  0]]]


Producto punto

In [41]:
print(-1*tensor)
print(np.array([1,2,3])*tensor)
print(np.array([[1,2,3],[4,5,6],[7,8,9]])*tensor)
print(tensor*tensor)


[[[ 1  0 -1]
  [-1 -1  0]
  [ 0  0  1]]

 [[ 0 -1 -1]
  [-1  0  1]
  [ 1  1  0]]]
[[[-1  0  3]
  [ 1  2  0]
  [ 0  0 -3]]

 [[ 0  2  3]
  [ 1  0 -3]
  [-1 -2  0]]]
[[[-1  0  3]
  [ 4  5  0]
  [ 0  0 -9]]

 [[ 0  2  3]
  [ 4  0 -6]
  [-7 -8  0]]]
[[[1 0 1]
  [1 1 0]
  [0 0 1]]

 [[0 1 1]
  [1 0 1]
  [1 1 0]]]


Producto tensorial

In [43]:
ref_vector = np.array([1,2,3])
generated_tensor = np.tensordot(ref_vector,ref_vector,axes=0)
print(generated_tensor)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [47]:
generated_tensor = np.tensordot(matriz,ref_vector,axes=1)
print(generated_tensor)

[ 8 15]


In [50]:
generated_tensor = np.tensordot(matriz,tensor,axes=2)
print(generated_tensor)

[-2 -1  0]


In [51]:
generated_tensor = np.tensordot(matriz,matriz,axes=2)
print(generated_tensor)

24


In [49]:
generated_tensor = np.tensordot(tensor,tensor,axes=3)
print(generated_tensor)

11
