## Manipulación de arrays

#### Entorno de ejecución

In [16]:
import numpy as np

In [17]:
tensor = np.random.randint(1,5,(3,2,3))
print(tensor)

[[[1 1 2]
  [1 1 2]]

 [[3 3 1]
  [1 3 2]]

 [[1 3 2]
  [3 3 4]]]


### ravel()
Reordena un array a uno de dimensión cero.

In [18]:
vector = tensor.copy()
vector = vector.ravel()
print(tensor, vector)

[[[1 1 2]
  [1 1 2]]

 [[3 3 1]
  [1 3 2]]

 [[1 3 2]
  [3 3 4]]] [1 1 2 1 1 2 3 3 1 1 3 2 1 3 2 3 3 4]


### split()
Divide un array de dimensión uno en varios arrays con un mismo numero de elementos.

In [19]:
array = np.random.randint(5,20,20)
print(array)
matriz_split = np.split(array, 2)
print(matriz_split)
matriz_split = np.split(array, 4)
print(matriz_split)

[ 8  7  5  7 12 13 12 11 16  5 15 14 17 15 10 18  8  8 16 14]
[array([ 8,  7,  5,  7, 12, 13, 12, 11, 16,  5]), array([15, 14, 17, 15, 10, 18,  8,  8, 16, 14])]
[array([ 8,  7,  5,  7, 12]), array([13, 12, 11, 16,  5]), array([15, 14, 17, 15, 10]), array([18,  8,  8, 16, 14])]


### insert()
Añade elementos al array

$$np.insert(arreglo,\ posición,\ valores)$$

In [20]:
array = np.insert(array,obj=10,values=[1,0,1])
print(array)

[ 8  7  5  7 12 13 12 11 16  5  1  0  1 15 14 17 15 10 18  8  8 16 14]


### append()
Añade elementos al final del array

$$np.append(arreglo,\ valores)$$

In [21]:
array = np.append(array, [-1,0,1])
print(array)

[ 8  7  5  7 12 13 12 11 16  5  1  0  1 15 14 17 15 10 18  8  8 16 14 -1
  0  1]


### delete()
Elimina elementos del arreglo según su posición.

$$np.delete(arreglo,\ obj\ =\ posición)$$

In [22]:
array = np.delete(array,obj=-2)
print(array)

[ 8  7  5  7 12 13 12 11 16  5  1  0  1 15 14 17 15 10 18  8  8 16 14 -1
  1]
